export type Lang = "zh-CN" | "en-US";

export interface Messages {
  title: string;
  subtitle: string;
  scanPc: string;
  selectProject: string;
  localReadonly: string;
  scanningTitle: string;
  scanningPath: string;
  scanningPython: string;
  scanningNode: string;
  scanningGit: string;
  scanningProject: string;
  back: string;
  newScan: string;
  selectAnotherProject: string;
  resultsTitle: string;
  problems: string;
  warnings: string;
  checksOk: string;
  findingsTitle: string;
  noFindings: string;
  evidence: string;
  recommendation: string;
  limitations: string;
  copyForAi: string;
  saveReport: string;
  copied: string;
  copyFailed: string;
  saveSuccess: string;
  saveFailed: string;
  project: string;
  python: string;
  node: string;
  path: string;
  git: string;
  system: string;
  noProject: string;
  projectRequirements: string;
  currentEnv: string;
  privacy: string;
  generatedBy: string;
  scanError: string;
  chooseProjectTitle: string;
  saveTitle: string;
  markdownFilter: string;
}

export const messages: Record<Lang, Messages> = {
  "zh-CN": {
    title: "为什么你的项目又跑不起来了？",
    subtitle:
      "EnvCompass 检查你的开发环境，找出 runtime、PATH 与项目要求之间的冲突。",
    scanPc: "扫描这台电脑",
    selectProject: "选择项目文件夹",
    localReadonly: "本地运行 · 只读 · 无遥测",
    scanningTitle: "正在检查开发环境…",
    scanningPath: "正在检查 PATH…",
    scanningPython: "正在检查 Python…",
    scanningNode: "正在检查 Node.js…",
    scanningGit: "正在检查 Git…",
    scanningProject: "正在读取项目要求…",
    back: "返回",
    newScan: "重新扫描这台电脑",
    selectAnotherProject: "选择另一个项目",
    resultsTitle: "扫描结果",
    problems: "个问题",
    warnings: "个警告",
    checksOk: "项检查正常",
    findingsTitle: "发现的问题",
    noFindings: "未发现明确的环境冲突。",
    evidence: "证据",
    recommendation: "建议",
    limitations: "说明",
    copyForAi: "复制给 AI",
    saveReport: "保存报告",
    copied: "已复制到剪贴板",
    copyFailed: "复制失败，请手动选择并复制",
    saveSuccess: "报告已保存",
    saveFailed: "保存失败",
    project: "项目",
    python: "Python",
    node: "Node.js",
    path: "PATH",
    git: "Git",
    system: "系统",
    noProject: "未选择项目",
    projectRequirements: "项目要求",
    currentEnv: "当前环境",
    privacy: "本地运行 · 只读 · 报告默认脱敏",
    generatedBy: "Generated by EnvCompass",
    scanError: "扫描失败",
    chooseProjectTitle: "选择要扫描的项目文件夹",
    saveTitle: "保存诊断报告",
    markdownFilter: "Markdown 文件",
  },
  "en-US": {
    title: "Why won't your project run again?",
    subtitle:
      "EnvCompass checks your development environment for conflicts between runtimes, PATH, and project requirements.",
    scanPc: "Scan this PC",
    selectProject: "Select project folder",
    localReadonly: "Local · Read-only · No telemetry",
    scanningTitle: "Checking development environment…",
    scanningPath: "Checking PATH…",
    scanningPython: "Checking Python…",
    scanningNode: "Checking Node.js…",
    scanningGit: "Checking Git…",
    scanningProject: "Reading project requirements…",
    back: "Back",
    newScan: "Scan this PC again",
    selectAnotherProject: "Select another project",
    resultsTitle: "Scan results",
    problems: "problems",
    warnings: "warnings",
    checksOk: "checks OK",
    findingsTitle: "Findings",
    noFindings: "No clear environment conflict was found.",
    evidence: "Evidence",
    recommendation: "Recommendation",
    limitations: "Note",
    copyForAi: "Copy for AI",
    saveReport: "Save report",
    copied: "Copied to clipboard",
    copyFailed: "Copy failed. Please select and copy manually.",
    saveSuccess: "Report saved",
    saveFailed: "Save failed",
    project: "Project",
    python: "Python",
    node: "Node.js",
    path: "PATH",
    git: "Git",
    system: "System",
    noProject: "No project selected",
    projectRequirements: "Project requirements",
    currentEnv: "Current environment",
    privacy: "Local · Read-only · Reports are sanitized by default",
    generatedBy: "Generated by EnvCompass",
    scanError: "Scan failed",
    chooseProjectTitle: "Choose a project folder to scan",
    saveTitle: "Save diagnosis report",
    markdownFilter: "Markdown files",
  },
};

export function detectLanguage(): Lang {
  return navigator.language.toLowerCase().startsWith("zh") ? "zh-CN" : "en-US";
}

